# Generated by Django 3.2 on 2024-03-20 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_Add_user_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGenreBaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг категории')),
            ],
        ),
    ]
