# Generated by Django 3.2 on 2024-03-20 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_Add_category_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('categorygenrebasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='genres', serialize=False, to='reviews.categorygenrebasemodel')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'default_related_name': 'genres',
            },
            bases=('reviews.categorygenrebasemodel',),
        ),
    ]
