# Generated by Django 3.2 on 2024-03-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_Add_gener_title_cross_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCommentBaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('text', models.TextField()),
            ],
        ),
    ]
